### ISSUE TITLE
Mettre en place le service d'authentification Hydra

### ISSUE THREAD

**Issue by follyjohn** [Neighbook/Infrastructure#7]
Le but est de Configurer, deployer et de rendre disponible un service d'authentification base sur un Fork de [ory/hydra](https://github.com/ory/hydra)

Pour ce faire il faudrais :

- [ ] Forker le projet https://github.com/ory/hydra
- [ ] Modifier la base de code si besoin
- [ ] Mettre en place le pipeline de dev , de test et de  deployement
- [ ] Creer un Azure Container registry pour accullir les image de la solution builder
- [ ] Deployer et configuer une image qui repond aux besoin du projet sur Azure Container App

Une attention particuliere devra etre conscédé lors l'uilisation et des modification de ory/hydra car sous licence [Apache-2.0](https://www.apache.org/licenses/LICENSE-2.0)

**Comment by kilian-goetz** [comment]
@follyjohn 

Dernier semestre, on était sur Azure, on avait regardé avec @Valentin271 pour déployer le serveur hydra, c'était un enfer. Quel était la techno utilisée le dernier semestre pour gérer l'authentification ?

Sachant que ce semestre, on hébergera en on-premise, on pourra beaucoup plus facilement faire un serveur hydra.

**Comment by follyjohn** [comment]
Hello, le semestre dernier on avais un service d'authentification coder par mes soins, mais on vas sauter ce service et deployer un service d'authent

**Comment by kilian-goetz** [comment]
Oui, il vaut mieux utiliser des services d'authentification basée sur des protocoles sécurisés vu que cette application vient à être déployé.

**Comment by Valentin271** [comment]
@Beladric close pls
